### ISSUE TITLE
0.86.0 keine Aktualisierung möglich

### ISSUE THREAD

**Issue by JBSullivan** [inventwo/ioBroker.vis-icontwo#285] opened 2022-02-13 20:30 UTC
![image](https://user-images.githubusercontent.com/44617472/153773640-54438354-4924-48a7-82ad-12c88bad8483.png)

Admin 5.3.0
js-controller 3.3.22

`$ iobroker upgrade vis-icontwo@0.86.0

Update vis-icontwo from @0.85.0 to @0.86.0

NPM version: 6.14.11

npm install iobroker.vis-icontwo@0.86.0 --loglevel error (System call)

npm ERR! code EPERM npm ERR! syscall rename npm ERR! path C:\iobroker\GLT\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate npm ERR! dest C:\iobroker\GLT\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate npm ERR! errno -4048 npm ERR! Error: EPERM: operation not permitted, rename 'C:\iobroker\GLT\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\iobroker\GLT\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate' npm ERR! [OperationalError: EPERM: operation not permitted, rename 'C:\iobroker\GLT\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\iobroker\GLT\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] { npm ERR! cause: [Error: EPERM: operation not permitted, rename 'C:\iobroker\GLT\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\iobroker\GLT\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] { npm ERR! errno: -4048, npm ERR! code: 'EPERM', npm ERR! syscall: 'rename', npm ERR! path: 'C:\\iobroker\\GLT\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate', npm ERR! dest: 'C:\\iobroker\\GLT\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate' npm ERR! }, npm ERR! errno: -4048, npm ERR! code: 'EPERM', npm ERR! syscall: 'rename', npm ERR! path: 'C:\\iobroker\\GLT\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate', npm ERR! dest: 'C:\\iobroker\\GLT\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate', npm ERR! parent: 'npm' npm ERR! } npm ERR! npm ERR! The operation was rejected by your operating system. npm ERR! It's possible that the file was already in use (by a text editor or antivirus), npm ERR! or that you lack permissions to access it. npm ERR! npm ERR! If you believe this might be a permissions issue, please double-check the npm ERR! permissions of the file and its containing directories, or try running npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: npm ERR! C:\iobroker\GLT\env\npm-cache\_logs\2022-02-13T20_23_29_397Z-debug.log

host.GLT(GLT) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248

ERROR: Process exited with code 25`

**Comment by sigi2345** [comment] 2022-02-14 12:05
Bei mir auch, Windows System

NODE.JS: V14.19.0
NPM: 6.14.16
JS Controller: 4.0.9
Admin: 5.3.0
Web: 4.1.3
Socket.io: 4.1.0
Script Engine: 5.2.19

**Comment by skvarel** [comment] 2022-02-14 15:03
Merkwürdig.

Hier lief das Update gestern problemlos durch. Ich hatte extra gewartet, bis der ioBroker mir das Update angeboten hat.

Rasbian OS
NODE.JS: 16.13.2
NPM: 8.1.2
JS Controller: 4.0.9
Admin: 5.3.0
Web: 4.1.3
VIS: 1.4.12
Socket.io: 4.1.2
Script Engine: 5.2.21

![image](https://user-images.githubusercontent.com/1114419/153888406-f26062b3-17b0-4f20-b20e-691357815fc1.png)

**Comment by skvarel** [comment] 2022-02-14 15:05
@jkvarel  .. kannst du mal bitte ein Adapter-Update auf deinem Windows-System machen und dann hier eine kurze Rückmeldung geben?

**Comment by jkvarel** [comment] 2022-02-14 16:49
Lief auf meinem Test-System ohne Probleme durch. War aber auch eine neu Installation, da ich das System neu aufsetzen musste. Hat aber nichts mit dem Fehler zu tun. 

Tritt der Fehler nur bei dem Adapter auf oder auch bei anderen? Zur Not Adapter einmal deinstallieren und wieder installieren

**Comment by JBSullivan** [comment] 2022-02-14 18:11
Heute, nach dem anheben auf js-controlle 4.0.9 habe ich nochmal einen Versuch unternommen. Allerdings aus der Konsole heraus und nicht aus dem Admin. Da gab es die folgenden Meldungen.

`Would you like to upgrade vis-icontwo from @0.85.0 to @0.86.0 now? [(y)es, (n)o]: y
Update vis-icontwo from @0.85.0 to @0.86.0
NPM version: 6.14.11
Installing iobroker.vis-icontwo@0.86.0... (System call)
host.GLT(GLT) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248
Cannot find io-package.json in C:/iobroker/GLT/node_modules/iobroker.vis-icontwo
Could not read io-package.json: ENOENT: no such file or directory, open 'C:\iobroker\GLT\node_modules\iobroker.vis-icontwo\io-package.json'
Cannot parse C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json: C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json: ENOENT: no such file or directory, open 'C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json'
Cannot find io-package.json in C:/iobroker/GLT/node_modules/iobroker.vis-icontwo
Could not read io-package.json: ENOENT: no such file or directory, open 'C:\iobroker\GLT\node_modules\iobroker.vis-icontwo\io-package.json'
INFO: Directory "C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/admin" was not found! Nothing was uploaded or deleted.
 Cannot find view "system" for search "instance" : Connection is closed.
Cannot check dependencies: Cannot find view "system"`

Aus Admin heraus  gab es dann wieder die folgenden Meldungen - 

$ iobroker upgrade vis-icontwo@0.86.0

Update vis-icontwo from @0.85.0 to @0.86.0

NPM version: 6.14.11

Installing iobroker.vis-icontwo@0.86.0... (System call)

host.GLT(GLT) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248

Cannot find io-package.json in C:/iobroker/GLT/node_modules/iobroker.vis-icontwo

Could not read io-package.json: ENOENT: no such file or directory, open 'C:\iobroker\GLT\node_modules\iobroker.vis-icontwo\io-package.json'

Cannot parse C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json: C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json: ENOENT: no such file or directory, open 'C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/io-package.json'

Cannot find io-package.json in C:/iobroker/GLT/node_modules/iobroker.vis-icontwo

Could not read io-package.json: ENOENT: no such file or directory, open 'C:\iobroker\GLT\node_modules\iobroker.vis-icontwo\io-package.json'

INFO: Directory "C:/iobroker/GLT/node_modules/iobroker.vis-icontwo/admin" was not found! Nothing was uploaded or deleted.

ERROR: Process exited with code 25

**Comment by sigi2345** [comment] 2022-02-14 18:28
> Tritt der Fehler nur bei dem Adapter auf oder auch bei anderen?

Auch bei andere, da half immer vorher den Adapter zu stoppen.

**Comment by JBSullivan** [comment] 2022-02-14 18:38
Das Icon Set hat ja keinen Stop Button. Bei anderen Adapter kam dann unter Windows immer ein EBUSY Fehler, wenn man die Instanz nicht vorher gestoppt hat. Bei den Icons gibt es aber gar keine Instanz die man stoppen könnte - außerdem "sollte" das mit dem EBUSY Fehler ggf. unter js-controller 4.0.9 nicht mehr auftreten.

**Comment by sigi2345** [comment] 2022-02-14 18:43
> Das Icon Set hat ja keinen Stop Button.

Jupp

**Comment by sigi2345** [comment] 2022-02-14 21:42
> außerdem "sollte" das mit dem EBUSY Fehler ggf. unter js-controller 4.0.9 nicht mehr auftreten.

Ja, laut @apollon77 sollte das so sein, liegt eher an NPM

**Comment by jkvarel** [comment] 2022-02-15 16:09
> Komischer weise sind die Icons aber da?
> 
> ![Screenshot (4752)](https://user-images.githubusercontent.com/41079106/153924510-707f0455-61d5-4927-ae1b-9a3e75862260.png)


Das ist eine externe Seite, die da angezeigt wird

**Comment by sigi2345** [comment] 2022-02-16 16:31
![Screenshot (4768)](https://user-images.githubusercontent.com/41079106/154311470-39bf1bea-33ba-43f9-836d-ad09f7ef178c.png)

**Comment by jkvarel** [comment] 2022-02-16 18:46
Ist anscheinend ein Problem mit dem js-controller. Issue dafür hat @sigi2345 schon erstellt
https://github.com/ioBroker/ioBroker.js-controller/issues/1808

**Comment by Apollon77** [comment] 2022-02-16 18:50
It more seems to be an issue with npm on windows ... and now it starts to become meeeehh ... yes there is "somthing" with controller 4.0.10 too that will be fixed in 4.0.11 but this is not the root cause. the permission errors are :-(

**Comment by Apollon77** [comment] 2022-02-16 19:10
is really also controlelr 3.3.22 afected? Thsi it is definitively something with npm

**Comment by JBSullivan** [comment] 2022-02-16 20:37
Hier noch zwei Meldungen, welche direkt nach dem ioB Neustart OHNE Installationsversuch ins Protokoll geschrieben wurden. Vielleicht hilft es den Fehler einzugrenzen. js-controller ist 4.0.10

`<html>
<body>


host.GLTGLT) |   | 2022-02-16 21:33:03.165 | error | host.GLT(GLT) iobroker npm-install: adapter "vis-icontwo" cannot be installed: Cannot destructure property 'stoppedList' of '(intermediate value)' as it is undefined.
-- | -- | -- | -- | --
host.GLTGLT) |   | 2022-02-16 21:33:03.115 | error | host.GLT(GLT) iobroker npm-install: host.GLT(GLT) Cannot install iobroker.vis-icontwo@0.86.0: 4294963248


</body>
</html>`

**Comment by Apollon77** [comment] 2022-02-16 21:54
According to @sigi2345 issues start with 0.82 ... here the "Incliuded npm" was updated to 8.0.0 ... BUT WHY THERE IS AN NPM INSIDE?????? @jkvarel

**Comment by Apollon77** [comment] 2022-02-16 21:56
@JBSullivan Diese "stoppedList" Fehler sind ein indirekter Folgefehler des anderen Issues ... die mache ich noch weg, aber die sind nur beiwerk quasi

**Comment by jkvarel** [comment] 2022-02-18 18:36
> According to @sigi2345 issues start with 0.82 ... here the "Incliuded npm" was updated to 8.0.0 ... BUT WHY THERE IS AN NPM INSIDE?????? @jkvarel

I don't know. In the package-lock.json? If I remove it, it will work? I checked the vis-inventwo adapter and there is no npm

**Comment by skvarel** [comment] 2022-02-19 07:33
> @jkvarel what about https://github.com/inventwo/ioBroker.vis-icontwo/blob/master/package.json#L29 ... clearly states npm as dependency and this dep was increased in 0.82 ... release it

@Apollon77 .. can I just delete this line?

![image](https://user-images.githubusercontent.com/1114419/154791607-c2c3761a-cdc0-4439-9b63-923610bf932f.png)

**Comment by skvarel** [comment] 2022-02-19 07:36
> @jkvarel what about https://github.com/inventwo/ioBroker.vis-icontwo/blob/master/package.json#L29 ... clearly states npm as dependency and this dep was increased in 0.82 ... release it

Eigentlich können dort doch alle Dependencies raus, oder? Es ist nur ein Icon Adapter ohne weiteren Code.

**Comment by skvarel** [comment] 2022-02-19 08:07
v0.86.2 ... wrong npm version in dependencies fixed

Pls try the 0.68.2

**Comment by skvarel** [comment] 2022-02-19 08:20
@sigi2345  ..  @JBSullivan

**Comment by sigi2345** [comment] 2022-02-19 08:27
> Pls try the 0.68.2

?

**Comment by skvarel** [comment] 2022-02-19 09:41
> > Pls try the 0.68.2
> 
> ?

SORRY .. ich meinte natürlich 0.86.2 !!

**Comment by JBSullivan** [comment] 2022-02-19 09:49
Bei mir ist die Installation nun sauber durchgelaufen

![image](https://user-images.githubusercontent.com/44617472/154795866-012f5ca1-16db-4f94-9643-7a1be1e82918.png)

**Comment by skvarel** [comment] 2022-02-19 11:35
@jkvarel hat gerade noch mal etwas am Code optimiert und ich habe neue Icons hinzugefügt,

Die 0.87.0 sollte sich also auch per Update installieren lassen. Wartet bitte, bis der ioBroker euch das Update anzeigt. Könnt ihr mir hier dann eine kurze Rückmeldung geben?

Wenn das Update dann durchläuft, schliesse ich das Issue.

Vielen dank an @Apollon77 !!

**Comment by sigi2345** [comment] 2022-02-19 14:35
Mit Version 0.87.0 funktioniert wieder Alles.

**Comment by Apollon77** [comment] 2022-02-19 14:37
> Stable wird dann auch direkt für die 0.87.0 beantragt!

Den kriegste ausnahmsweise auch sofort :-)

War aber der einzige Adapter damit (haben alle gecheckt) :-)

**Comment by skvarel** [comment] 2022-02-19 15:32
Latest/Beta wird das Update bereits angeboten. Stable ist beantragt .... ich schließe dann hier ab.

![image](https://user-images.githubusercontent.com/1114419/154807483-dbfba091-8324-46b9-9470-a4388667ddc1.png)

**Closed by skvarel** 2022-02-19 15:32 UTC
Labels: bug
